name: solid_test
description: Test task
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5

dev_dependencies:

  flutter_test:
    sdk: flutter

  build_runner:
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4

  solid_lints: ^0.0.19
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app_icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 24
  adaptive_icon_background: "#C6C6C6"
  adaptive_icon_foreground: "app_icons/adaptive_icon_foreground.png"
  web:
    generate: true
    image_path: "app_icons/app_icon.png"
    background_color: "#C6C6C6"
    theme_color: "#FFFFFF"

flutter:

  uses-material-design: true
